---
title: "Seurat_scATAC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# This R markdown file was modified based on Signac (Seurat) tutorials.

# load packages
```{r, message = FALSE} 
library(Seurat)
library(ggplot2)
library(hdf5r)
library(rtracklayer)
library(Signac)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v86) # genome_build: GRCh38 !!!
set.seed(1234)
```


# add cut site matrix to signac object
```{r}
# load signac object (with peak profile)
signac.object <- readRDS("signac_object.rds")

# load count matrix by cut site (generated by step 3)
tmp <- readRDS("CutSites_count_byState_all.rds")

# add cut site matrix to signac object as the assay of "State15"
count.cs <- tmp[, rownames(signac.object@meta.data)]
rownames(count.cs) <- gsub("_", "-", rownames(count.cs))
signac.object[["State15"]] <- CreateAssayObject(counts = count.cs)
DefaultAssay(signac.object) <- "State15"
```


# dimension reduction & clustering
```{r}
# Normalization and linear dimensional reduction
signac.object <- RunTFIDF(signac.object, assay = "State15")
signac.object <- FindTopFeatures(signac.object, min.cutoff = 'q0')
signac.object <- RunSVD(signac.object, n=14)
DepthCor(signac.object)

# Non-linear dimension reduction and clustering
signac.object <- RunUMAP(object = signac.object, reduction = 'lsi', dims = 1:14)
signac.object <- FindNeighbors(object = signac.object, reduction = 'lsi', dims = 1:14)
signac.object <- FindClusters(object = signac.object, verbose = FALSE, algorithm = 3, resolution = 0.7) # tune the resolution until results are biological meaningful.
```


# save
```{r}
saveRDS(signac.object, file = "signac_object_new.rds")
```

