#!/bin/bash
#
#SBATCH --job-name=bash
#SBATCH -N 1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8g
#SBATCH -t 3-00:00 # Runtime in D-HH:MM
#SBATCH --output=split-%A_%a.out
#SBATCH --array=1-878 # Based on how many lists of barcode generated by step 1


# create a folder named "FragmentsbyCell" in the working directory
mkdir FragmentsbyCell

# specify fragment file direction
path=/FourPatients_aggr/4Patients_aggr/outs

# split fragment file by barcode
cat ./Barcode/BarcodeList_${SLURM_ARRAY_TASK_ID}.txt | while read line; do
  barcode=`echo $line | cut -f1 | sed 's/[\n\r\t]//g'`
  echo $barcode
  zgrep "$barcode" $path/fragments.tsv.gz > ./FragmentsbyCell/${barcode}.txt
done
